README.md
package.json

update:update dependencies

---

LICENSE
dist/index.js
package.json
src/utils/selectCanvas.js

add: license

---

dist/index.js
package.json
src/canvas/baseCanvas.js

add : link:connect event

---

.gitignore
README.md
dist/index.js
package.json
src/canvas/baseCanvas.js
src/canvas/baseCanvas.less
src/group/baseGroup.js
src/group/baseGroup.less
src/node/baseNode.js

添加节点组可修改大小 & 修复draw方法返回值 & 修改文档

添加节点组可修改大小 & 修复draw方法返回值 & 修改文档

---

package.json
src/canvas/baseCanvas.js
src/endpoint/baseEndpoint.js
src/group/baseGroup.js

线条去重 & 过滤右键事件

---

README.md
package.json
src/canvas/baseCanvas.js
src/utils/coordinate.js

聚焦功能加强，支持多节点聚焦，全画布聚焦

---

README.md
package.json
src/canvas/baseCanvas.js

添加group增加删除节点的功能

---

package.json
src/canvas/baseCanvas.js

添加: group resize 事件

---

README.md
package.json
src/canvas/baseCanvas.js
src/edge/baseEdge.js
src/endpoint/baseEndpoint.js
src/group/baseGroup.js
src/node/baseNode.js

添加group endpoint的功能 & 支持连线连接group

添加group endpoint的功能 & 支持连线连接group

---

README.md
package.json
src/canvas/baseCanvas.js
src/edge/baseEdge.js
src/endpoint/baseEndpoint.js
src/group/baseGroup.js
src/node/baseNode.js

添加global的配置

---

README.md
package.json
src/canvas/baseCanvas.js
src/group/baseGroup.js

修复group里面addNodes和rmNodes的方法，方便大家都代码添加节点

修复group里面addNodes和rmNodes的方法，方便大家都代码添加节点

---

package.json
src/canvas/baseCanvas.js

修复removeEdge的bug

---

package.json
src/canvas/baseCanvas.js
src/group/baseGroup.js

支持group addnode

---

README.md
package.json
src/canvas/baseCanvas.js
src/edge/baseEdge.js
src/endpoint/baseEndpoint.js
src/group/baseGroup.js
src/utils/scopeCompare.js

支持group添加锚点而且不需要添加任何字段 & 支持节点和节点组的作用域

支持group添加锚点而且不需要添加任何字段 & 支持节点和节点组的作用域

---

docs/edge.md
docs/endpoint.md
package.json
src/canvas/baseCanvas.js
src/endpoint/baseEndpoint.js
src/node/baseNode.js

add: 添加复杂线条处理事件 & 禁止锚点断开线段

---

src/canvas/baseCanvas.js
src/canvas/baseCanvas.less
src/group/baseGroup.js
src/group/baseGroup.less
src/node/baseNode.js
src/utils/girdService.js
src/utils/guidelineService.js
src/utils/selectCanvas.js

- addEventLinster -> addEventListener
- warpper -> wrapper

Fix var name

---

src/edge/baseEdge.js
src/edge/baseEdge.less
src/utils/arrow.js

fix:优化箭头样式,逻辑

---

src/utils/arrow.js

fix: path error

---

src/utils/arrow.js

V2.3，箭头方向bugfix

---

src/utils/guidelineService.js

解决网格吸附画布中辅助线1px模糊问题

---

src/canvas/baseCanvas.js

线条的箭头dom跟着线条走，而不是统一append到svg里面

线条的箭头dom跟着线条走，而不是统一append到svg里面

---

src/canvas/baseCanvas.js

修复zoom事件监听返回的zoom系数不准确

---

src/canvas/baseCanvas.js
src/edge/baseEdge.js
src/utils/link.js

fix: neighborNodesAndEdges return value
feat: manhattan router

feat & fix

---

docs/canvas.md
package-lock.json
src/edge/baseEdge.js
src/utils/link.js

update: advanced bezier link

---

README.en-US.md
README.md
package.json
src/canvas/baseCanvas.js

添加demo到readme

---

package.json
src/canvas/baseCanvas.js

fix: zoom的差值为0时不会执行回调

---

docs/en-US/minimap.md
docs/zh-CN/minimap.md
src/canvas/baseCanvas.js
src/utils/minimap.js

- 完美支持缩放，拖动
- 支持小地图中节点高亮
- 更加优秀的用户体验，限制用户将视口拖出 minimap

feat: 更完美的minimap

---

.gitignore
docs/en-US/canvas.md
docs/en-US/endpoint.md
docs/zh-CN/canvas.md
docs/zh-CN/endpoint.md
package.json
src/canvas/baseCanvas.js
src/endpoint/baseEndpoint.js
src/node/baseNode.js

feat： supprot set linkable，dislinkable，draggable

feat： supprot set linkable，dislinkable，draggable

---

src/utils/toolTip.js

fix:creatMenus' callBackFunc returns more values,

---

example/demo/concent-layout/center.js
example/demo/concent-layout/center.less
example/demo/concent-layout/data.js
example/demo/concent-layout/edge.js
example/demo/concent-layout/index.jsx
example/demo/concent-layout/index.less
example/demo/concent-layout/node.js
example/demo/concent-layout/node.less
example/index.jsx
src/canvas/baseCanvas.js
src/utils/layout/layout.js

同心圆布局和demo

---

example/demo/circle/centerNode.js
example/demo/circle/circleCanvas.js
example/demo/circle/data.js
example/demo/circle/group.js
example/demo/circle/group.less
example/demo/circle/index.jsx
example/demo/circle/node.js
example/demo/circle/node.less
example/package.json

Cirle layout

---

example/demo/circle/circleCanvas.js
example/demo/circle/data.js
example/demo/circle/group.js
example/demo/circle/index.jsx
example/demo/circle/node.less
example/demo/circle/noteSourceNode.js
example/demo/circle/noteTargetNode.js
src/edge/baseEdge.js
src/group/baseGroup.js

feat: add notes

---

example/demo/rule-tree/custom.js
example/demo/rule-tree/index.jsx
example/demo/rule-tree/node.js
example/demo/rule-tree/node.less
src/canvas/treeCanvas.js

feat: treeCanvas优化

---

docs/zh-CN/canvas.md

typo: Object structure is not correct

---

src/utils/arrow.js

fix: _ is not defined

---

example/demo/schedule/data.js
src/canvas/baseCanvas.js
src/group/baseGroup.js

Group组件支持配置draggable
group节点配置优先级高于全局配置

[Group]: support config draggable

---

src/canvas/treeCanvas.js

fix: issue #9
删除节点后，如果这个节点有父节点，应该将此节点从父节点的children中移除

fix:remove nodes

---

src/canvas/baseCanvas.js

#355 , 修正theme.endpoint.limitNum失效问题

bugfix: #355 theme.endpoint.limitNum invalid

---

docs/en-US/layout.md
docs/zh-CN/layout.md

decs: change layout.md

---

docs/zh-CN/react.md

修改了react组件的文档中的用法。
Modified the usage in the react.md（docs/zh-CN/react.md）

modify react.md

---

example/demo/drageLayout/drageCanvas.js

修复this.canvas.drageReDraw(newOptions);界面排序问题

fix: drageReDraw for drageLayout demo

---

README.en-US.md
README.md
docs/en-US/react.md
docs/en-US/vue.md
docs/zh-CN/vue.md
react/package.json
vue/butterfly-vue.css
vue/butterfly-vue.vue
vue/coms/Vue-group.vue
vue/coms/Vue-node.vue
vue/coms/edge.js
vue/coms/group.js
vue/coms/node.js
vue/index.js
vue/package.json
vue/rollup.config.js
vue/util/add-com.js
vue/util/addCom.js
vue/util/default-data.js
vue/util/diff.js
vue/util/process.js
vue/util/re-calc.js
vue/util/re-layout.js

up vue version

---

example/demo/mindMap/index.jsx
example/demo/rule-tree/node.js

fix: 修改引用变量的问题

---

README.en-US.md
README.md
docs/en-US/tooltip.md

feat: add tips docs

---

.npmignore
package.json
src/endpoint/baseEndpoint.js
src/utils/toolTip.js

fix: endpoint calc width & height

fix: endpoint calc width & height

---

README.en-US.md
README.md

feat: add react components docs

feat: add react components docs

---

docs/en-US/canvas.md
docs/en-US/edge.md
docs/zh-CN/canvas.md
docs/zh-CN/edge.md
example/demo/compact-box-tree/index.jsx
example/demo/compact-box-tree/node.js
package.json
src/canvas/baseCanvas.js
src/edge/baseEdge.js

feat: add set edge z-index

---

example/demo/schedule/edge.js
example/demo/schedule/index.jsx
example/demo/schedule/node.js
package.json
src/canvas/baseCanvas.js

fix: node, group, edge z-index

fix: node, group, edge z-index

---

package.json
src/canvas/baseCanvas.js

fix: edge label z-index bug

---

docs/zh-CN/group.md
docs/zh-CN/node.md

Revert "修改节点"

---

.gitignore
package.json
webpack.config.js

- feat: 增加 `unpkg` 的构建形式 & 修改 `main` 为非压缩 `commonjs` 的格式

feat(webpack): no minify after build

---

src/edge/baseEdge.js

- fix: syntax error to `require` link util

fix: syntax for require

---

example/demo/fishbone/data.js
example/demo/fishbone/edge.js
example/demo/fishbone/index.jsx
example/demo/fishbone/index.less
example/demo/fishbone/node.js
example/demo/fishbone/node.less
example/index.jsx
src/utils/layout/fishboneLayout.js
src/utils/layout/layout.js

Ref #588 
可到example/demo/fishbone/data.js详见传入参数以及数据，目前5层嵌套还没有发现问题。
注：本pr仍缺少许多功能，也欢迎在当前代码的基础上提出缺少的功能/可以优化的功能。
注：传参options相关说明：
``` js
/**
* @param {number} top
*  Fishbone offset's distance to top
*/
top: 300,
/**
* @param {number} left
*  Fishbone offset's distance to left
*/
left: 600,
/**
* @param {string} mdoe
*  Show mode of Fishbone layout，
*  now there're 2 mode:coincide(default), space-even.
*  If not set, value=coincide.
*/
mode: 'coincide',
/**
* @param {bool} reversed
*  Fishbone's default direction is right.
*  If reversed is true, direction change to left. 
*  If not set, value=false.
*/
reversed: true,
/**
* @param {number} mainAxisLength
*  Fishbone's main axis length.
*  If not set, the length will depends on 1st level children counts.
*/
mainAxisLength: 2000,
/**
* @param …
```

[Fishbone]: basic fishbone algorithms. Ref #588

---

react/index.jsx
react/package.json

fix minimap bug

---

react/package.json
react/util/process.js

user node,edge,group Class

---

react/index.jsx
react/package.json

bugfix: alignNodesCls

---

vue/butterfly-vue.vue
vue/example/src/App.vue
vue/example/src/page/radial/node/radial-node.vue
vue/example/src/page/radial/radial-mockData.js
vue/example/src/page/radial/radial.vue
vue/example/src/page/treeDemo/index.vue
vue/example/src/router.js
vue/package.json
vue/util/process.js
vue/util/re-layout.js

fix: 修复layout bug以及添加radial demo

---

vue/butterfly-vue.vue
vue/example/package.json
vue/example/src/page/base/base.vue
vue/example/src/page/base/edgeLabel/base-label.vue
vue/example/src/page/drag/drag.vue
vue/example/src/page/emergency/edgeLabel/base-label.vue
vue/example/src/page/treeDemo/index.vue
vue/example/src/page/userEndpoint/node/endpoint-node.vue
vue/package.json
vue/util/add-com.js
vue/util/process.js
vue/util/re-layout.js

feat: 支持直接修改canvasData

---

vue/example/package.json
vue/example/src/page/base/base.vue
vue/package.json
vue/util/re-layout.js

发布 1.0.7
修复： 没有设置layout，也layout导致的bug

fix: 没有设置layout也去layout的bug

---

plugins/panel/src/index.js

fix: 修复panel-plugins的宽高没传的问题(issues#673)

---

package.json
src/canvas/baseCanvas.js

fix: 修复锚点限制的提示以及重连没有排除当前线的bug(issues#694)

---

vue/package.json
vue/util/add-com.js

发布butterfly-vue@1.0.8版本

---

docs/en-US/canvas.md
docs/zh-CN/canvas.md
src/canvas/baseCanvas.js

feat: 添加触发锚点限制的emit(issues:#698 )

---

docs/en-US/vue.md
docs/zh-CN/vue.md
vue/coms/vue-endpoint.vue
vue/example/src/App.vue
vue/example/src/page/base/base.vue
vue/example/src/page/grid/grid.vue
vue/example/src/page/userEndpoint/node/endpoint-node.vue
vue/package.json
vue/util/add-com.js

feat：支持自定义锚点参数传入

---

vue/package.json
vue/util/add-com.js
vue/util/process.js

fix: 修复一个页面多个canvas导致的渲染问题

---

docs/en-US/canvas.md
docs/zh-CN/canvas.md
src/canvas/baseCanvas.js

feat: 支持config传递z-index参数

---

package.json
src/canvas/baseCanvas.js

fix: check repeat

---

webpack.config.js

fix: 调整编译，编译d3和ml-matrix中箭头函数，支持ie11

fix: 调整编译，编译d3和ml-matrix中箭头函数，支持ie11

---

package.json
src/canvas/baseCanvas.js

[fix: getNeighborNodes bug](https://github.com/alibaba/butterfly/commit/6f48a897ec22452144bd3a002cc7de9a8d4c66f7)

fix: getNeighborNodes bug
